# .gitlab-ci.yml

stages:
  - build
  - test

# Define the job that builds your application
build:
  stage: build
  image: node:latest
  script:
    - npm install --legacy-peer-deps
    - npm run build
  artifacts:
    paths:
      - build/

# Define the job that runs linting and tests
test:
  stage: test
  image: node:latest
  script:
    - npm install --legacy-peer-deps
    - npm run lint-code
    - npm run lint-style
    - npm run test
